apiVersion: v1
kind: ServiceAccount
metadata:
  name: apiadmin
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apiadmin-clusterrole
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets", "nodes", "pods", "services", "resourcequotas", "replicationcontrollers", "limitranges", "persistentvolumeclaims", "persistentvolumes", "namespaces", "endpoints"]
  verbs: ["create", "delete", "get", "list", "patch", "watch"]
- apiGroups: ["extensions"]
  resources: ["daemonsets", "deployments", "replicasets", "ingresses"]
  verbs: ["create", "delete", "get", "list", "patch", "watch"]
- apiGroups: ["apps"]
  resources: ["statefulsets", "daemonsets", "deployments", "replicasets"]
  verbs: ["create", "delete", "get", "list", "patch", "watch"]
- apiGroups: ["batch"]
  resources: ["cronjobs", "jobs"]
  verbs: ["create", "delete", "get", "list", "patch", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: apiadmin-clusterrole-binding
subjects:
- kind: ServiceAccount
  name: apiadmin
  namespace: default
roleRef:
  kind: ClusterRole
  name: apiadmin-clusterrole
  apiGroup: rbac.authorization.k8s.io